// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDV6cThkSGlV-btuei-i3lf17lJeQDkkkc',
    appId: '1:107524300965:web:274df78ffdd4e4cdd1ed4c',
    messagingSenderId: '107524300965',
    projectId: 'example-recipe-app-d72c1',
    authDomain: 'example-recipe-app-d72c1.firebaseapp.com',
    storageBucket: 'example-recipe-app-d72c1.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDioF5G6lwYnqqLQO9DAvBtrSnW1SV_9ok',
    appId: '1:107524300965:android:1f6240f7c3ede2afd1ed4c',
    messagingSenderId: '107524300965',
    projectId: 'example-recipe-app-d72c1',
    storageBucket: 'example-recipe-app-d72c1.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDMHuk1X740IPan2VXAqO6m6kOiwBOvefM',
    appId: '1:1023575489869:ios:8689d1fd917f7def97cb04',
    messagingSenderId: '1023575489869',
    projectId: 'recipe-app-16f8a',
    storageBucket: 'recipe-app-16f8a.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDMHuk1X740IPan2VXAqO6m6kOiwBOvefM',
    appId: '1:1023575489869:ios:8689d1fd917f7def97cb04',
    messagingSenderId: '1023575489869',
    projectId: 'recipe-app-16f8a',
    storageBucket: 'recipe-app-16f8a.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD2SrzbXdjYzCHmHoR2x2Do1JQnMN8IkN8',
    appId: '1:1023575489869:web:b26e6375476e1d2697cb04',
    messagingSenderId: '1023575489869',
    projectId: 'recipe-app-16f8a',
    authDomain: 'recipe-app-16f8a.firebaseapp.com',
    storageBucket: 'recipe-app-16f8a.firebasestorage.app',
  );
}