// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCoKWgPXpGKhFnbC0adNjrALVs2LtTif0U',
    appId: '1:241594561616:web:065cf7cd4681b6a787cd55',
    messagingSenderId: '241594561616',
    projectId: 'example-recipe-app-5e590',
    authDomain: 'example-recipe-app-5e590.firebaseapp.com',
    storageBucket: 'example-recipe-app-5e590.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBKeGi0jaB4TDraGoPbWqE_E3YtTLPDmoM',
    appId: '1:241594561616:android:11a918b61679ccdd87cd55',
    messagingSenderId: '241594561616',
    projectId: 'example-recipe-app-5e590',
    storageBucket: 'example-recipe-app-5e590.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_m0Ohjb5Gjnb-13hw0JiDBpalbF_N8rI',
    appId: '1:336003961732:ios:a9d1a65f8ee8016e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_m0Ohjb5Gjnb-13hw0JiDBpalbF_N8rI',
    appId: '1:336003961732:ios:a9d1a65f8ee8016e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCoKWgPXpGKhFnbC0adNjrALVs2LtTif0U',
    appId: '1:241594561616:web:ee00c3a44360da4e87cd55',
    messagingSenderId: '241594561616',
    projectId: 'example-recipe-app-5e590',
    authDomain: 'example-recipe-app-5e590.firebaseapp.com',
    storageBucket: 'example-recipe-app-5e590.firebasestorage.app',
  );

}