// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDLT5mDjSC5DKHBAXXOC7UfOHSlq__uZwk',
    appId: '1:336003961732:web:aadd79b43a615ad20503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    authDomain: 'test-genkit-64288.firebaseapp.com',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDk84-rE2iUEx3psDibsRWsISP03U8uun4',
    appId: '1:336003961732:android:1163df3c5207c53e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB_m0Ohjb5Gjnb-13hw0JiDBpalbF_N8rI',
    appId: '1:336003961732:ios:a9d1a65f8ee8016e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB_m0Ohjb5Gjnb-13hw0JiDBpalbF_N8rI',
    appId: '1:336003961732:ios:a9d1a65f8ee8016e0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
    iosBundleId: 'com.example.recipeApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDLT5mDjSC5DKHBAXXOC7UfOHSlq__uZwk',
    appId: '1:336003961732:web:1f0183faccabcedc0503d1',
    messagingSenderId: '336003961732',
    projectId: 'test-genkit-64288',
    authDomain: 'test-genkit-64288.firebaseapp.com',
    storageBucket: 'test-genkit-64288.firebasestorage.app',
  );

}